name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set env as secret
      env:
        MY_VAL: ${{ secrets.CONNECTION_STRING }}
      run: |
        import os
        for q in (os.getenv("MY_VAL")):
          print(q)
      shell: python
