name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        DEBUG_PASSWORD: ${{ secrets.CONNECTION_STRING }}
      run: |
        echo $DEBUG_PASSWORD

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
